version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logstash_logs:1:1,api:1:1,batch:1:1"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    links:
      - zookeeper
    depends_on:
      - zookeeper
    container_name: kafka
  logstash:
    image: logstash:8.7.1
    ports:
      - "10000:10000"
    links:
      - kafka
    volumes:
      - ./logstash_settings/:/usr/share/logstash/config/
      - ./logstash_pipeline/:/usr/share/logstash/pipeline/
    container_name: logstash
  kafka-sec:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-sec:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sec-logstash:1:1,sec-api:1:1"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zookeeper
    depends_on:
      - zookeeper
    container_name: kafka-sec